#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from newpackage
import newpackage
from newpackage.lib import clean_data

if __name__ == '__main__':
    try_me()
